---
- project:
    name: openstack-k8s-operators/heat-operator
    github-check:
      jobs:
        - openstack-k8s-operators-content-provider
        - heat-operator-tempest-multinode
        - heat-operator-tempest-multinode-ceph
